spring:
  datasource:
    url: jdbc:mysql://blog-mysql:3306/blog_database?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8080
  address: 0.0.0.0  # 绑定到所有网络接口